export enum ErrorCode {
    // Command lifecycle / runtime
    CMD_CONFLICT_ALIAS = "CMD_CONFLICT_ALIAS",

    // Decorators
    DECORATOR_INVALID_ALIAS = "DECORATOR_INVALID_ALIAS",
    DECORATOR_MISSING_REQUIRED_INFORMATION = "DECORATOR_MISSING_REQUIRED_INFORMATION",

    // Validation
    VALIDATION_MISSING_REQUIRED_PROPERTY = "VALIDATION_MISSING_REQUIRED_PROPERTY",
    VALIDATION_INVALID_TYPE = "VALIDATION_INVALID_TYPE",

    // Parser
    PARSER_UNKNOWN_FLAG = "PARSER_UNKNOWN_FLAG",
    PARSER_MISSING_VALUE = "PARSER_MISSING_VALUE",

    // Loader
    LOADER_INVALID_CMD = "LOADER_INVALID_CMD",

    // Internal
    INTERNAL_UNEXPECTED = "INTERNAL_UNEXPECTED"
}